version: '3.8'

services:
    dev:
        container_name: demo-ecommerce-dev
        image: nestjs-api-dev:latest
        build:
            context: .
            target: development
            dockerfile: ./docker/Dockerfile
        command: yarn run start:debug
        ports:
            - 9229:9229
        networks:
            - nesjs-network
        volumes:
            - .:/usr/src/app
            - /usr/src/app/node_modules
        restart: unless-stopped
    prod:
        container_name: demo-ecommerce-prod
        image: nestjs-api-prod:latest
        build:
            context: .
            target: production
            dockerfile: ./docker/Dockerfile
        command: yarn run start:prod
        ports:
            - 9229:9229
        networks:
            - nesjs-network
        volumes:
            - .:/usr/src/app
            - /usr/src/app/node_modules
        restart: unless-stopped

networks:
    nesjs-network: